### ISSUE TITLE
Nach dem Login lande ich auf dem Login Server

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/rw-remote-auth-client#15]
Wenn ich mich neu auf einem Client anmelde und noch nicht auf dem AUTH Server angemeldet war lande ich im Adminbereich des Login-Servers,

**Comment by staude** [comment]
Du meinst, der CAS Server redirected dich nicht zurück zum Client?

**Comment by johappel** [comment]
hat sich erledigt, Liegt am Boss.Theme
