### ISSUE TITLE
remote_login_referrer wird nicht gelöscht

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/rw-remote-auth-client#19]
ich komme im boss theme nicht ins backend, weil der remote_login_referrer cookie nicht gelöscht wird.

**Comment by staude** [comment]
Gerde auf reliwerk.de mit staude und test123456 ausprobiert, klappt Problemlos.
Auf welcherm Server und mit welchem User tritt das Problem auf?

**Comment by staude** [comment]
Auch mit dem Boss Theme kann ich das Problem auf der VM nicht nachvollziehen.
Ich schliesse das Ticket mal. Bitte ggf wieder öffnen wenn es erneut auftritt bzw reproduzierbar ist.
