### ISSUE TITLE
Passwort muss nach der Anmeldung neu registriert werden

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/rw-remote-auth-client#24]
http://support.rpi-virtuell.de/scp/tickets.php?id=198
Wie hier beschrieben und von mir in gruppen.rpi-virtuell.de nachvollzogen müssen sie neue Nutzer oft nach der Registrierung das Passwort neu zuweisen lassen. Offenbar wird es nicht mit cas synchronisiert.

**Comment by staude** [comment]
an das Ticket komm ich nicht ran
Zugang verweigert. Kontaktieren Sie Ihren Administrator wenn Sie glauben, dass dies ein Fehler ist

**Comment by johappel** [comment]
Wurde in 0.2.10 gefixed
