### ISSUE TITLE
in gruppen können normale user nicht mehr ihr passwort ändern

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/rw-remote-auth-client#28]
das passiert, wenn das passwort in einer anderen Instanz oder nur im login geändert wurde.
Dann stimmt das alte passwort nicht mehr überein und die Änderung wird nicht durchgeführt.

**Comment by staude** [comment]
Kann ich gerade nicht testen, weil ich bei dem neuen User keine Emailadresse angeben kann bzw die Meldung kommt, das die Emailadresse bereits verwendet wird. Könnte aber auch der gleiche Fehler sein.
